

DROP TABLE IF EXISTS `CLIENTES`;

CREATE TABLE CLIENTES (
  ID_CLIENTE    int NOT NULL AUTO_INCREMENT,
  NOMBRE_CL     varchar(100) DEFAULT NULL,
  EMAIL         varchar(100) DEFAULT NULL,
  TLF_CL        varchar(20) DEFAULT NULL,
  PASS          varchar(100) DEFAULT NULL,
  FECHA_ALTA    date DEFAULT NULL,
  PUNTOS        int DEFAULT NULL,
  PRIMARY KEY (ID_CLIENTE),
  UNIQUE KEY EMAIL  (EMAIL),
  UNIQUE KEY TLF_CL (TLF_CL)
)



DROP TABLE IF EXISTS `MENU`;

CREATE TABLE MENU (
  ID_PLATO      int NOT NULL AUTO_INCREMENT, 
  NOMBRE_PL     varchar(100) DEFAULT NULL,
  DESCRIPCION   varchar(255) DEFAULT NULL,
  PRECIO        float DEFAULT NULL,
  PUNTOS_PL     int DEFAULT NULL,
  PRIMARY KEY (ID_PLATO)
)

DROP TABLE IF EXISTS `RESTAURANTE`;

CREATE TABLE RESTAURANTE (
  ID_RESTAURANTE int NOT NULL ,
  NOMBRE_REST varchar(100) DEFAULT NULL,
  TLF_REST varchar(20) DEFAULT NULL,
  DIRECCION varchar(255) DEFAULT NULL,
  COD_POSTAL varchar(10) DEFAULT NULL,
  PRIMARY KEY (ID_RESTAURANTE),
  UNIQUE KEY TLF_REST (TLF_REST)
) 

DROP TABLE IF EXISTS `PEDIDOS`;

CREATE TABLE `PEDIDOS` (
  ID_PEDIDO       int NOT NULL AUTO_INCREMENT,
  ID_CLIENTE      int DEFAULT NULL,
  ID_RESTAURANTE  int DEFAULT NULL,
  FECHA_PEDIDO    date DEFAULT NULL,
  PRECIO_TOTAL    float DEFAULT NULL,
  PUNTOS_PED      int DEFAULT NULL,
  PRIMARY KEY (ID_PEDIDO),
  KEY ID_CLIENTE (ID_CLIENTE),
  KEY ID_RESTAURANTE (ID_RESTAURANTE),
  CONSTRAINT `pedidos_ibfk_1` FOREIGN KEY (ID_CLIENTE) REFERENCES `clientes` (ID_CLIENTE),
  CONSTRAINT `pedidos_ibfk_2` FOREIGN KEY (ID_RESTAURANTE) REFERENCES `restaurante` (ID_RESTAURANTE)
)
